name: Forest
version: '${project.version}'
main: me.emmy.hub.Forest
author: Emmy
description: '${project.description}'
website: https://discord.gg/U6FTRKycsf
depends:
  - PlaceholderAPI
  - ProtocolLib